//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocs.DomainModels.Database
{
    using System;
    using System.Collections.Generic;
    
     using WebDocs.DomainModels.Interfaces.Entities;
    public partial class EmailSetting: IEntity
    {
        public int ID { get; set; }
    	
        public string UserName { get; set; }
    	
        public string Password { get; set; }
    	
        public string SmtpHost { get; set; }
    	
        public int SmtpPort { get; set; }
    	
        public bool SslEnabled { get; set; }
    	
        public string SystemEmailAddress { get; set; }
    	
    		public EntityState EntityState { get; set; }
    		}
}
