//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocs.DomainModels.Database
{
    using System;
    using System.Collections.Generic;
    
     using WebDocs.DomainModels.Interfaces.Entities;
    public partial class EmailCacheModel: IEntity
    {
        public int EmailCacheID { get; set; }
    	
        public string EmailMessage { get; set; }
    	
        public bool HasBeenSent { get; set; }
    	
        public int RetryAttempt { get; set; }
    	
        public int IDOfPersonSender { get; set; }
    	
        public int IDOfRecipient { get; set; }
    	
        public string EmailSubject { get; set; }
    	
    		public EntityState EntityState { get; set; }
    		
        public virtual UsersModel EmailSender { get; set; }
        public virtual UsersModel EmailRecipient { get; set; }
    }
}
