//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocs.DomainModels.Database
{
    using System;
    using System.Collections.Generic;
    
     using WebDocs.DomainModels.Interfaces.Entities;
    public partial class FileModel: IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileModel()
        {
            this.FileArchives = new HashSet<FileArchiveModel>();
            this.FileCategories = new HashSet<FileCategoryModel>();
            this.PrivateFilesSharedWithUsers = new HashSet<PrivateFilesSharedWithUserModel>();
            this.FileNotifications = new HashSet<NotificationModel>();
            this.SystemTransactionLogs = new HashSet<SystemTransactionLogsModel>();
        }
    
        public int FileID { get; set; }
    	
        public int UserIDOfFileOwner { get; set; }
    	
        public int UserIDOfLastUploaded { get; set; }
    	
        public int FileLookupStatusID { get; set; }
    	
        public int FileShareStatusID { get; set; }
    	
        public string ContentType { get; set; }
    	
        public string Name { get; set; }
    	
        public string Extension { get; set; }
    	
        public int Size { get; set; }
    	
        public int CurrentVersionNumber { get; set; }
    	
        public System.DateTime Created { get; set; }
    	
    		public EntityState EntityState { get; set; }
    		
        public virtual UsersModel FileOwner { get; set; }
        public virtual UsersModel PersonThatLastUpdatedFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileArchiveModel> FileArchives { get; set; }
        public virtual FileBlobModel FileBlob { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileCategoryModel> FileCategories { get; set; }
        public virtual FileStatusModel FileViewStatuses { get; set; }
        public virtual FileShareStatusModel FileShareStatues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateFilesSharedWithUserModel> PrivateFilesSharedWithUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationModel> FileNotifications { get; set; }
        public virtual UserThatDownloadedFileModel UserThatDownloadedFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemTransactionLogsModel> SystemTransactionLogs { get; set; }
    }
}
