//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocs.DomainModels.Database
{
    using System;
    using System.Collections.Generic;
    
     using WebDocs.DomainModels.Interfaces.Entities;
    public partial class FileArchiveModel: IEntity
    {
        public int FileArchiveID { get; set; }
    	
        public int FileID { get; set; }
    	
        public int UserIDOfLastUploaded { get; set; }
    	
        public string ContentType { get; set; }
    	
        public string Name { get; set; }
    	
        public string Extension { get; set; }
    	
        public int Size { get; set; }
    	
        public int Version { get; set; }
    	
        public System.DateTime DateCreated { get; set; }
    	
        public System.DateTime DateArchived { get; set; }
    	
    		public EntityState EntityState { get; set; }
    		
        public virtual FileModel File { get; set; }
        public virtual FileArchiveBlobModel FileArchiveBlob { get; set; }
        public virtual UsersModel UserThatUploadedTheFile { get; set; }
    }
}
