//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocs.DomainModels.Database
{
    using System;
    using System.Collections.Generic;
    
     using WebDocs.DomainModels.Interfaces.Entities;
    public partial class FileCategoryModel: IEntity
    {
        public int FileCategoryID { get; set; }
    	
        public int FileID { get; set; }
    	
        public int LookupTableFileCategoryID { get; set; }
    	
    		public EntityState EntityState { get; set; }
    		
        public virtual CategoriesModel FileCategories { get; set; }
        public virtual FileModel File { get; set; }
    }
}
