//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocs.DomainModels.Database
{
    using System;
    using System.Collections.Generic;
    
     using WebDocs.DomainModels.Interfaces.Entities;
    public partial class NotificationModel: IEntity
    {
        public int NotificationID { get; set; }
    	
        public int FileID { get; set; }
    	
        public int NotificationTypeID { get; set; }
    	
        public System.DateTime DateCreated { get; set; }
    	
        public int UserIDOfNotificationSender { get; set; }
    	
        public int UserIDOfNotificationRecipient { get; set; }
    	
        public bool UserHasAcknowledgement { get; set; }
    	
    		public EntityState EntityState { get; set; }
    		
        public virtual UsersModel SendingUsers { get; set; }
        public virtual UsersModel RecipientUsers { get; set; }
        public virtual NotificationTypesModel NotificationTypes { get; set; }
        public virtual FileModel File { get; set; }
    }
}
