//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocs.DomainModels.Database
{
    using System;
    using System.Collections.Generic;
    
     using WebDocs.DomainModels.Interfaces.Entities;
    public partial class UsersModel: IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersModel()
        {
            this.PrivateFilesSharedWithUsers = new HashSet<PrivateFilesSharedWithUserModel>();
            this.SenderNotifications = new HashSet<NotificationModel>();
            this.RecipientNotifications = new HashSet<NotificationModel>();
            this.UserChats = new HashSet<UserChatModel>();
            this.UserThatDownloadedFiles = new HashSet<UserThatDownloadedFileModel>();
            this.OwnerFiles = new HashSet<FileModel>();
            this.PersonThatLastUpdatedFile = new HashSet<FileModel>();
            this.FileArchives = new HashSet<FileArchiveModel>();
            this.EmailCaches = new HashSet<EmailCacheModel>();
            this.EmailCaches1 = new HashSet<EmailCacheModel>();
            this.SystemTransactionLogs = new HashSet<SystemTransactionLogsModel>();
        }
    
        public int Id { get; set; }
    	
        public string Email { get; set; }
    	
        public bool EmailConfirmed { get; set; }
    	
        public string PasswordHash { get; set; }
    	
        public string SecurityStamp { get; set; }
    	
        public string PhoneNumber { get; set; }
    	
        public bool PhoneNumberConfirmed { get; set; }
    	
        public bool TwoFactorEnabled { get; set; }
    	
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
    	
        public bool LockoutEnabled { get; set; }
    	
        public int AccessFailedCount { get; set; }
    	
        public string UserName { get; set; }
    	
        public string FirstName { get; set; }
    	
        public string LastName { get; set; }
    	
    		public EntityState EntityState { get; set; }
    		
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrivateFilesSharedWithUserModel> PrivateFilesSharedWithUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationModel> SenderNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationModel> RecipientNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChatModel> UserChats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserThatDownloadedFileModel> UserThatDownloadedFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileModel> OwnerFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileModel> PersonThatLastUpdatedFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileArchiveModel> FileArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailCacheModel> EmailCaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailCacheModel> EmailCaches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemTransactionLogsModel> SystemTransactionLogs { get; set; }
    }
}
