//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDocsEntities : DbContext
    {
        public WebDocsEntities()
            : base("name=WebDocsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<EmailSendLog> EmailSendLogs { get; set; }
        public virtual DbSet<EmailSetting> EmailSettings { get; set; }
        public virtual DbSet<FileBlob> FileBlobs { get; set; }
        public virtual DbSet<FileCategory> FileCategories { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileSharedWithUser> FileSharedWithUsers { get; set; }
        public virtual DbSet<LookupTable_FileCategories> LookupTable_FileCategories { get; set; }
        public virtual DbSet<LookupTable_FileShareStatues> LookupTable_FileShareStatues { get; set; }
        public virtual DbSet<LookupTable_FileViewStatuses> LookupTable_FileViewStatuses { get; set; }
        public virtual DbSet<LookupTable_NotificationTypes> LookupTable_NotificationTypes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserChat> UserChats { get; set; }
        public virtual DbSet<UserThatDownloadedFile> UserThatDownloadedFiles { get; set; }
    }
}
