//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSendLog
    {
        public int EmailSendID { get; set; }
        public int UserThatSentID { get; set; }
        public string ToAddress { get; set; }
        public string FromAddress { get; set; }
        public string FromName { get; set; }
        public string Message { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
