//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChat
    {
        public int UserChatID { get; set; }
        public int ChatID { get; set; }
        public int UserID { get; set; }
        public string Message { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Chat Chat { get; set; }
    }
}
